name: GCP Deployment via WIF

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write   # required to mint the OIDC token
  contents: read    # Required to read the repository content

jobs:
  workload-identity-federation:
    runs-on: ubuntu-latest  
    steps:
      # Step 1: Initialize the runner workspace with your repository
      - name: Checkout Repository
        uses: actions/checkout@v4


       # Step 2: Exchange the GitHub OIDC token for a short-lived GCP token
      - name: Authenticate to Google Cloud via WIF
        uses: google-github-actions/auth@v2
        with:
            workload_identity_provider: projects/project-47caaef7-3623-4070-b93/locations/global/workloadIdentityPools/github-actions/providers/github
            service_account: cgep-grc-gate-sa@project-47caaef7-3623-4070-b93.iam.gserviceaccount.com

        # Step 3: Automatically configure the local gcloud CLI to use the WIF token
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Step 4: Run your test command
      - name: List Storage Buckets
        run: gcloud storage ls